### PR TITLE
Mark setDefaultTopicConf as deprecated

### PR DESCRIPTION
**Pull request by KonstantinCodes**
See: https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/rdkafka-conf.setdefaulttopicconf.html

### CODE REVIEW

**Comment by nick-zh** [comment]
@KonstantinCodes great stuff, thx, can you maybe check if this also up to date for `setLogLevel` and `setLogger` which were also deprecated?

**Comment by KonstantinCodes** [comment]
Thanks for the pointer!

`RdKafka::setLogger` is not in the stubs, but `RdKafka::setLogLevel` is, so I marked it as deprecated.

**Comment by nick-zh** [comment]
@KonstantinCodes awesome thx
@kwn lgtm

**Comment by kwn** [comment]
Thank you guys!!

Merged and published in 2.0.4.

**Pull request merged**
