### PR TITLE
Make payload nullable for compacted topics / tombstones

### PR DESCRIPTION
**Pull request by silentgecko**
https://kafka.apache.org/documentation/#design_compactionbasics
Compacted Topics and Tombstones have a key set, but payload is null

### CODE REVIEW

**Comment by nick-zh** [comment]
Totally agree, i created #41 to fix the build, once it is merged you can update your branch :+1:

**Comment by kwn** [comment]
Hi @nick-zh and @silentgecko 

Could you please rebase your branch with the latest master? I merged #41 so hopefully it's going to work now.

**Comment by silentgecko** [comment]
@kwn  done :)

**Review by nick-zh — APPROVED** [review]

**Comment by nick-zh** [comment]
@silentgecko thx, it's released as well :v:

**Comment by kwn** [comment]
Thanks guys 👍

**Pull request merged**
